### PR TITLE
Provide GNU-style build system

### PR DESCRIPTION
**Pull request by ismaell**

### CODE REVIEW

**Comment by alexfru** [comment]
If you really want to build the compiler from the sources and install it, so it can be used as intended (i.e. `smlrcc` would be able to find the headers and the libraries and compile a hello-world-style app simply with `smlrcc hw.c -o hw`), you need to also build the libraries as a next step and then copy them and the header files to under `/usr/local/smlrc/include` and `/usr/local/smlrc/lib`. Otherwise, it's a half-baked thing, not aiding much. One could just compile the three executables and copy them over to `usr/local/bin` in 4 simple commands with a much shorter script than these of yours. Could you cover this as well?

**Comment by ismaell** [comment]
Thanks, I'll try to address that. My intention was to check out if it would be accepted, and to solve my particular use case (I'm using only -flat16).

**Comment by alexfru** [comment]
Improvements are welcome and I will consider every request, but I can't guarantee everything will be accepted.

**Comment by ismaell** [comment]
Fixed. I made this version compatible with BSD make, just in case it comes useful later.

Do you mind if I change the way it installs to comply with the FHS? that would be installing headers to $(prefix)/include/smlrc and libraries to $(prefix)/lib/smlrc. and patching the search functions. Also, I see there's some room for de-duplication there.

**Comment by alexfru** [comment]
OK, how does one use these files *exactly*?
Simple
~~~
./configure
make install
~~~
doesn't cut it on my Ubuntu 12:
~~~
make: *** No rule to make target `smlrc', needed by `install'.  Stop.
~~~

If I copy the two files into `v0100` and try from there, I get:
~~~
gcc -Wall -O2 -DHOST_LINUX    smlrc.c   -o smlrc
gcc -Wall -O2 -DHOST_LINUX    smlrl.c   -o smlrl
gcc -Wall -O2 -DHOST_LINUX    smlrcc.c   -o smlrcc
awk -vl=/srclib/ '/[.](c|asm)$/{$0=l$0}{print}' srclib/lcdh.txt > lcdh.op
./smlrcc -SI /include -I /srclib @lcdh.op
nasm: fatal: unable to open output file `/srclib/c0dh.o'

Failed command 'nasm -f elf /srclib/c0dh.asm -o /srclib/c0dh.o'
make: *** [lcdh.a] Error 255
~~~

Comments?

**Comment by ismaell** [comment]
The "!=" assignment operator was added to GNU make 4.0, in Ubuntu 12 you can use pmake instead.

**Comment by alexfru** [comment]
I'm not happy with makefiles and such using many tools and requiring the latest versions of them. Smaller C itself, if you haven't noted yet, is written in ANSI C (except its C++-style comments, which arrived in C99, 15 years ago, anyway) and requires nothing outside the standard library and is compilable with pretty much any reasonable C compiler. I'm not happy with such scripts in Smaller C, with having to use some other tools or telling others to use some other tools to do a simple job. If you can make the scripts for the task more modest in their requirements, I'll take them. Otherwise, I will not.

**Comment by ismaell** [comment]
OK. I split it into three files so that there are no conflicts, now it should work with older GNU make.

**Comment by alexfru** [comment]
Not quite, the current directory is not in PATH:
~~~
$ make install
gcc -pipe -Wall -O2 -DHOST_LINUX    /home/alex/SmallerC/v0100/smlrc.c   -o smlrc
gcc -pipe -Wall -O2 -DHOST_LINUX    /home/alex/SmallerC/v0100/smlrl.c   -o smlrl
gcc -pipe -Wall -O2 -DHOST_LINUX    /home/alex/SmallerC/v0100/smlrcc.c   -o smlrcc
awk -vl=/home/alex/SmallerC/v0100/srclib/ '/[.](c|asm)$/{$0=l$0}{print}' /home/alex/SmallerC/v0100/srclib/lcdh.txt > lcdh.op
./smlrcc -SI /home/alex/SmallerC/v0100/include -I /home/alex/SmallerC/v0100/srclib @lcdh.op
sh: 1: smlrc: not found

Failed command 'smlrc -SI /home/alex/SmallerC/v0100/include -I /home/alex/SmallerC/v0100/srclib -huge -D _DOS -Wall /home/alex/SmallerC/v0100/srclib/c0.c /home/alex/SmallerC/v0100/srclib/c0.asm'
make: *** [lcdh.a] Error 255
rm lcdh.op
~~~
Looks like you first need to place the 3 executables in their destination directory (`/usr/local/bin`) and only then proceed to compilation of the libraries.

**Comment by ismaell** [comment]
Solved. Sorry, I had it installed already and forgot about the detail.

**Comment by alexfru** [comment]
Last step: some kind of `rm smlrcc smlrc smlrl lcdh.a lcds.a lcw.a lcl.a`? It's kinda bad to leave behind temp files, especially created with root privileges (smlrcc smlrc smlrl) and requiring extra effort to delete.

**Comment by ismaell** [comment]
The "clean" target does just that... but there's no reason to build as root, is it?

**Comment by alexfru** [comment]
Well, if I do `make install`, it fails to copy files to `usr/local/...`. If I do `sudo make install`, it works. Am I doing something wrong?

**Comment by ismaell** [comment]
You can do this instead: ```sh
make && sudo make install
```

**Comment by Zardoz89** [comment]
How far is compatible with old Make ??

**Comment by ismaell** [comment]
Well, in regard to the GNUmakefile, took care this time, tested on 3.80 (2002), may work fine on much older versions.

**Comment by alexfru** [comment]
@Zardoz89 Works on Ubuntu 12.04 LTS.

**Comment by alexfru** [comment]
@ismaell Sorry, for this having taken so long. Accepting! :)

**Pull request merged**
