### PR TITLE
dpstub: alloc dpmi mem in UMB

### PR DESCRIPTION
**Pull request by stsp**
This reduces the amount of used conventional memory.

### CODE REVIEW

**Comment by alexfru** [comment]
What would be the scenarios where this is important? How much does this save?

Also, it seems like this is DOS 5.0+ functionality whereas Smaller C so far only requires 4.01+.

On top of that, it looks like the strategy needs to be queried (functions 5800H, 5802H), then changed and then restored to the results of the initial query before the program terminates.

**Comment by stsp** [comment]
> What would be the scenarios where this is important?

For example the command-line shell.
This is my scenario exactly.
The fewer bytes the shell eats in a DOS
space, the more memory remains for
the spawned programs.

> How much does this save?

Depends on a DPMI server.
But usually in a range of 4K.

> On top of that, it looks like the strategy needs to be queried

OK, will do.

> P.S. I'm not seeing the DPMI 0.9 spec explicitly prohibiting the DPMI host private data in a UMB, but I wonder
> if it may cause problems.

No, it can't cause problems because
djgpp does the same:
https://github.com/jwt27/djgpp-cvs/blob/master/src/stub/stub.asm#L781-L819
But it does save/restore.
I wonder why I didn't just copy/pasted
from there... This is what I will do now.

**Comment by stsp** [comment]
All done.
djgpp code appears to check
the DOS version as well, so now
all should be good.

**Comment by stsp** [comment]
Resolved conflict with the prev patch.

**Comment by stsp** [comment]
Ping @alexfru what's the destiny
of this one?

**Comment by alexfru** [comment]
The destiny... We'll get there. I think, I need to introduce a few startup checks for DOS version and i80386+ before doing UMB.

**Comment by alexfru** [comment]
UMB linking is implemented. Seems to be saving approximately 8KB if CWSDPMI is also loaded while the UMB is linked.

**Pull request closed without merging**
